# Generated by Django 3.0.4 on 2020-05-11 15:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probetype',
            options={'verbose_name': 'Тип замера', 'verbose_name_plural': 'Типы замеров'},
        ),
        migrations.RemoveField(
            model_name='probe',
            name='profile',
        ),
        migrations.AddField(
            model_name='probe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 15, 22, 31, 907603, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 15, 22, 31, 908850, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 15, 22, 31, 908511, tzinfo=utc), verbose_name='Время создания'),
        ),
    ]
