# Generated by Django 3.0.4 on 2020-05-13 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200511_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Хэш пароля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_salt',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Соль пароля'),
        ),
    ]
