# Generated by Django 3.0.4 on 2020-06-02 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200601_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.MemberShip'),
        ),
    ]
