# Generated by Django 3.0.4 on 2020-06-07 09:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_message_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Дата генерации')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 6, 7, 9, 54, 32, 532973, tzinfo=utc), verbose_name='Дата окончания действия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Коды',
            },
        ),
    ]
